### ISSUE TITLE
您好，关于lolcat文本彩虹色显示的问题

### ISSUE THREAD

**Issue by potoo0** [andot/lolcat#1]
我按照您的教程美化和配置了powershell，但在您最新教程lolcat文本彩虹色显示的教程中安装了lolcat，但是没有彩虹效果，有时间了给我指点下好吗？

**Comment by andot** [comment]
你是在 powershell 里面执行的吗？执行之后显示什么样子，可以截个图看看吗？

**Comment by potoo0** [comment]
sorry。您的回复被我邮箱移动到垃圾箱了，一直没有看到。

**Comment by potoo0** [comment]
这是我的截图，popowershell修改了透明度，我本以为可能是透明度问题但改回透明度仍然没有彩色。


![screen1](https://user-images.githubusercontent.com/34411681/39848163-0958b3c4-5438-11e8-8b4b-09cfb5dbe5d5.png)
![screen2](https://user-images.githubusercontent.com/34411681/39848165-0d0d00d8-5438-11e8-9f1e-3c8db7782d6d.png)

**Comment by andot** [comment]
这个好奇怪，你的系统为何会屏蔽色彩转义码，我也不知道，而且你的命令行提示符明明是支持彩色的啊。搞不懂，搞不懂啊~

**Comment by potoo0** [comment]
颜色确实应该支持，show-themecolors都有颜色。

还是谢谢您的教程，现在界面已经很漂亮啦，谢谢。

**Comment by andot** [comment]
我刚刚更新了一下，不知道现在可不可以了。不过我觉得关系应该不大。

**Comment by potoo0** [comment]
em...
还是不行。。。，这个和所在文件夹没有关系吧？还有安装这个插件不需要其他安装目录等等的设置吗？
![screen](https://user-images.githubusercontent.com/34411681/39860881-838315c0-5471-11e8-8ee2-ef034e59d0c9.png)

**Comment by andot** [comment]
应该没有关系吧，我不管安装为全局的，还是当前用户的都可以正常显示。

**Comment by potoo0** [comment]
好吧，谢谢您不倦地回复。那我暂时放弃了，现在加上半透明也挺好看的，嘿嘿。

**Comment by astra-midnight** [comment]
Same issue, I'm not getting any color either. Show-themecolors shows color as well. I've tried it in both the builtin Powershell and Powershell 6. I'm using Fluent Terminal but that doesn't seem to make a difference as I can't get the color to show up anywhere.

**Comment by andot** [comment]
我发现是 Powershell 现在已经不支持 24bit 色的转义字符造成的（终端支持，但是 PowerShell 不支持）。

**Comment by astra-midnight** [comment]
Hmm, have you given https://github.com/poshcode/pansies a shot? It seems to address the issue for 24bit ansi support.

**Comment by johzzy** [comment]
已修复，详见 #3

**Comment by andot** [comment]
![image](https://user-images.githubusercontent.com/232161/71638566-6938b380-2c9e-11ea-8463-bf97e941b6b6.png)
感谢 @J0hmy 修正这个问题。
