### ISSUE TITLE
 Windows 10 自带的 PowerShell 环境下执行Install-Module lolcat -Scope CurrentUser 没有发生变化

### ISSUE THREAD

**Issue by Assassin-Neo** [andot/lolcat#2]
Windows 10 自带的 PowerShell 环境下执行Install-Module lolcat -Scope CurrentUser 没有发生变化，我的环境和您的一样，管理员下输入过：
**_Install-Module lolcat_**
常规窗口输入过：
_**Install-Module lolcat -Scope CurrentUser**_
均无效，现在很是费解。

**Comment by potoo0** [comment]
我的也是这样 T_T

**Comment by andot** [comment]
我也是这样 😂 
大概是新的 PowerShell 把 Write-Output 和 [Console]::Write 输出的彩色转义字符串给取消了？

**Comment by Assassin-Neo** [comment]
> 我也是这样 😂
> 大概是新的 PowerShell 把 Write-Output 和 [Console]::Write 输出的彩色转义字符串给取消了？

那您会随版本修复吗？；这个UI是真的cool😎

**Comment by andot** [comment]
这个好像是 PowerShell 不再默认开启 24 位色转义输出造成的。我去 PowerShell 的 git 项目里也没有找到可以用命令开启的方法。如果你找到方法的话，可以告诉我。

**Comment by Assassin-Neo** [comment]
好的，如果我找到的话一定会告知的。

**Comment by johzzy** [comment]
@Assassin-Neo 已修复，详见 #3

**Comment by andot** [comment]
@J0hmy 我合并代码之后，在 Windows 10 下面测试仍然没有颜色。

**Comment by johzzy** [comment]
@andot 使用下列代码测试一下, 最好截图
```
$text = "Hello,World"; $ESC = [char]27; $line = "$ESC[37;44;4;1m$text$ESC[0m"; Write-Output $line
Out-Rainbow qwertyuiopasdfghjkl0123456789
```
![image](https://user-images.githubusercontent.com/6779107/66266497-848b5280-e858-11e9-9556-76032c8d5e94.png)

**Comment by ZhaoKangming** [comment]
> @andot 使用下列代码测试一下, 最好截图
> 
> ```
> $text = "Hello,World"; $ESC = [char]27; $line = "$ESC[37;44;4;1m$text$ESC[0m"; Write-Output $line
> Out-Rainbow qwertyuiopasdfghjkl0123456789
> ```
> 
> ![image](https://user-images.githubusercontent.com/6779107/66266497-848b5280-e858-11e9-9556-76032c8d5e94.png)

hello, 我对您的此项目十分感兴趣，在您更新后我使用还是无效，附截图如下，请问您知道是什么原因么？
![Snipaste_2019-12-31_12-26-03.png](https://i.loli.net/2019/12/31/VowfFNG1E7kJASc.png)

**Comment by andot** [comment]
![image](https://user-images.githubusercontent.com/232161/71637932-3259a200-2c8c-11ea-9be7-dd82cf282ce3.png)

**Comment by andot** [comment]
OK，确实好了。非常感谢。

**Comment by andot** [comment]
发现 VSCode 也支持 24 位真彩色了。
![image](https://user-images.githubusercontent.com/232161/71638560-4ad2b800-2c9e-11ea-850c-aa9a98101b3d.png)
