### ISSUE TITLE
lolcat not working

### ISSUE THREAD

**Issue by DJMOJO** [andot/lolcat#4]
Out-String : Cannot validate argument on parameter 'Width'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not 
contain any null values and then try the command again.
At C:\Program Files\WindowsPowerShell\Modules\lolcat\1.0.7\lolcat.psm1:104 char:43
+ ... a | Out-String -Stream -Width $Host.UI.RawUI.WindowSize.Width | Out-S ...
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-String], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.OutStringCommand

**Comment by DJMOJO** [comment]
I just did Get-Host | lolcat but got the above error.

**Comment by andot** [comment]
<img width="648" alt="image" src="https://github.com/andot/lolcat/assets/232161/109eefd8-39e8-44b9-a9ec-7eeb11d087c5">

测试了一下，没有问题。我使用的 Windows 11。
